version: "3"

services:
  zookeeperservice:
    image: wurstmeister/zookeeper
    container_name: iamzookeepercontainer
    ports:
      - "2181:2181"

  kafkaservice:
    image: wurstmeister/kafka
    container_name: iamkafkacontainer
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeperservice:2181

    depends_on:
      - zookeeperservice

